# Generated by Django 4.1.3 on 2023-07-03 07:21

from django.db import migrations, models
import ocr.models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='text_name',
            field=models.CharField(default='bill', max_length=50),
        ),
        migrations.AlterField(
            model_name='upload',
            name='text_Img',
            field=models.ImageField(upload_to="images/"),
        ),
    ]
