# Generated by Django 4.1.3 on 2023-07-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_upload_text_name_alter_upload_text_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='text_name',
        ),
    ]
