# Generated by Django 4.1.3 on 2023-07-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_remove_upload_text_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='text_name',
            field=models.CharField(default='bill', max_length=50),
        ),
    ]
