# Generated by Django 4.1.3 on 2023-07-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_upload_text_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='text_name',
            field=models.CharField(max_length=50),
        ),
    ]
