# Generated by Django 4.1.3 on 2023-07-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_alter_upload_text_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='text_name',
            new_name='img_name',
        ),
    ]
