# Generated by Django 4.1.3 on 2023-07-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_remove_upload_img_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setTimer', models.IntegerField(max_length=122)),
            ],
        ),
    ]
